---
# Install desktop packages

- name: Add google-chrome repo
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: Add google-chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Enable canonical partners repo
  apt_repository: repo='deb http://archive.canonical.com/ubuntu xenial partner' state=present

- name: Add oracle java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install desktop packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - wine
    - google-chrome-stable
    - owncloud-client
    - nvidia-361
    - skype
    - virtualbox
    - oracle-java8-installer
