---
# Install common packages (console based)

- name: Update cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade installed packages
  become: yes
  apt: upgrade=dist

- name: Install required packages (console based)
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - mc
    - unrar  
    - htop
    - iftop
    - tcpdump
    - whois
    - wget
    - screen
    - tmux
    - curl
    - git
    - pwgen
    - lm-sensors
    - mdadm
    - smartmontools
    - smart-notifier
    - keychain

- include: profile.yml
