- name: Install vim packages
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - vim

- name: Make sure bundle directory exists
  file: path="~/.vim/bundle" state=directory

- stat: path=~/.vim/bundle/Vundle.vim
  register: vundle

- name: Checkout vundle repo
  git: repo=https://github.com/gmarik/vundle.vim.git dest="~/.vim/bundle/Vundle.vim"
  when: vundle.stat.exists == False

- name: Deploy vimrc config
  copy: src=.vimrc dest=~/.vimrc mode=0644

- name: Run bundle install
  shell: vim +BundleInstall +qall
