---
# Install desktop packages

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install desktop packages
  apt: name={{ item }} state=latest
  with_items:
    - virtualbox
